### ISSUE TITLE
Code Not Work

### ISSUE THREAD

**Issue by edanurr** [s-geissler/genetic-controller-placement#1]
Hello,
I am run this code but i am getting the following error:
"TypeError: coercing to Unicode: need string or buffer"

Can you help me?
Thank you so much.

**Comment by s-geissler** [comment]
This seems to be an issue with the version of python you are using.  Not sure which version exactly I used for this. I just made some minor changes and tried running it using `Python 2.7.16`, which worked without issues. Please try that.

**Comment by edanurr** [comment]
Hello, First of all thank you for your reply.
I was working python 2.7.13 before you answered. after you reply i upgrade
python3 for working in last version. i run this: "python3 main.py"
Now i am getting "TypeError: unorderable types: set() > int()" in 33. rows
of grap.py
Is this working method and python version true or false?
I would be very glad if you help.

Stefan Geißler <notifications@github.com>, 9 May 2019 Per, 12:22 tarihinde
şunu yazdı:

**Comment by s-geissler** [comment]
No, you should use `python2`. So call the program with `python2 main.py`. Before, remember to `git pull` the changes I made to the code a few hours ago.

I was getting the same error you got, but fixed it in the most recent version when running with `python2`.

**Comment by edanurr** [comment]
This code worked with python 2.7.13 after recent changes.
Thank you so much.

I have a little suggestion. it will be very useful if you write a summary of which logic works.

**Comment by s-geissler** [comment]
When I come around doing it, I will write a README to provide some guidance.

/closed
